name: CI
on:
  push:
    branches-ignore:
      - master
  pull_request:
  workflow_call:
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        jdk-version:
          - 8
          - 11
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: temurin
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Rename jar files
        working-directory: ./build/libs/
        run: |
          for name in $(find . -type f -name '*.jar'); do
            baseFileName=$(basename "$name" '.jar')
            mv "$name" "$baseFileName.jdk${{ matrix.jdk-version }}.jar"
          done
      - name: Upload a jar
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ matrix.jdk-version }}
          path: ./build/libs/
